=== ldittmar81/ioBroker_dashboard/schema/main.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Main Page Schema",
  "description": "Schema für die einzelnen Hauptseiten (z.B. Räume, Funktionen, Informationen)",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Der Name der Hauptseite (z.B. 'Räume').",
      "minLength": 1
    },
    "type": {
      "type": "string",
      "description": "Typ der Seite - auch Ordner für img und data/devices",
      "minLength": 1
    },
    "icon": {
      "type": "string",
      "description": "Der Name des FontAwesome-Icons (z.B. 'fa-door-open').",
      "pattern": "^fa[a-zA-Z-]*$"
    },
    "pin": {
      "type": "string",
      "description": "Optionale 4-stellige PIN.",
      "pattern": "^\\d{4}$"
    },
    "authorization": {
      "type": "array",
      "description": "Liste der autorisierten Benutzer.",
      "items": {
        "type": "string",
        "description": "Benutzername aus users.json"
      },
      "minItems": 1
    },
    "content": {
      "type": "array",
      "description": "Liste der Kategorien und deren Kacheln in der Hauptseite.",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "category": {
            "type": "string",
            "description": "Der Name der Kategorie (z.B. 'Erdgeschoss'). Kann leer sein.",
            "minLength": 0
          },
          "collapsed": {
            "type": "boolean",
            "description": "Kategorie ist zusammengeklappt"
          },
          "authorization": {
            "type": "array",
            "description": "Liste der autorisierten Benutzer auf Kategorieebene.",
            "items": {
              "type": "string",
              "description": "Benutzername aus users.json"
            },
            "minItems": 1
          },
          "tiles": {
            "type": "array",
            "description": "Liste der Kacheln in der Kategorie.",
            "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Der Name der Kachel (z.B. 'Wohn- und Esszimmer').",
                  "minLength": 1
                },
                "image": {
                  "type": "string",
                  "description": "Der Dateiname des Bildes (z.B. 'WohnEsszimmer.webp').",
                  "pattern": "^[a-zA-Z0-9_-]+\\.(webp|jpg|jpeg|png)$"
                },
                "authorization": {
                  "type": "array",
                  "description": "Liste der autorisierten Benutzer auf Kachelebene.",
                  "items": {
                    "type": "string",
                    "description": "Benutzername aus users.json"
                  },
                  "minItems": 1
                },
                "status": {
                  "type": "array",
                  "description": "Liste der Statusobjekte, die verschiedene Statuswerte anzeigen.",
                  "minItems": 0,
                  "items": {
                    "type": "object",
                    "properties": {
                      "label": {
                        "type": "string",
                        "description": "Das Label des Status (z.B. 'Lüftung').",
                        "minLength": 1
                      },
                      "value": {
                        "type": "string",
                        "description": "ID aus ioBroker (z.B. 'alias.0.Wohnzimmer.Durchlüftung.TIMER').",
                        "pattern": "^[a-zA-Z0-9_-]+\\.\\d+\\.[a-zA-Z0-9._-]+$"
                      },
                      "icon": {
                        "type": "string",
                        "description": "Der Name des FontAwesome-Icons (z.B. 'fa-wind').",
                        "pattern": "^fa[a-zA-Z-]*$"
                      },
                      "unit": {
                        "type": "string",
                        "description": "Die Einheit (z.B. '°C', '%', 'min').",
                        "minLength": 1
                      },
                      "decimal": {
                        "type": "integer",
                        "description": "Anzahl der Dezimalstellen (z.B. 2).",
                        "minimum": 0
                      },
                      "error": {
                        "type": "string",
                        "description": "Ausdruck für Fehlerbedingung (z.B. 'val == 0 || !val').",
                        "minLength": 1
                      },
                      "warning": {
                        "type": "string",
                        "description": "Ausdruck für Warnungsbedingung (z.B. 'val < 5').",
                        "minLength": 1
                      },
                      "alarm": {
                        "type": "boolean",
                        "description": "Warnung oder Fehler markanter anzeigen"
                      }
                    },
                    "required": [
                      "label",
                      "value"
                    ],
                    "additionalProperties": false
                  }
                }
              },
              "required": [
                "name",
                "status"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "category",
          "tiles"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "icon",
    "content"
  ],
  "additionalProperties": false
}

=== ldittmar81/ioBroker_dashboard/data/main/functions.json
{
  "name": "Funktionen",
  "type": "functions",
  "icon": "fa-cogs",
  "authorization": [
    "papa"
  ],
  "content": [
    {
      "category": "",
      "tiles": [
        {
          "name": "Licht",
          "image": "Licht.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Licht.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Licht.Status"
            }
          ]
        },
        {
          "name": "Dekorations Licht",
          "image": "DekorationsLicht.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.DekorationsLicht.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.DekorationsLicht.Status"
            }
          ]
        },
        {
          "name": "Fenster",
          "image": "Fenster.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Rollladen.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Rollladen.Status"
            }
          ]
        },
        {
          "name": "Heizung",
          "image": "Heizung.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Heizung.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Heizung.Status"
            }
          ]
        },
        {
          "name": "Haushalt",
          "image": "Haushalt.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Haushalt.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Haushalt.Status"
            }
          ]
        },
        {
          "name": "Gartenger√§te",
          "image": "Gartengeraete.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Gartengeraete.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Gartengeraete.Status"
            }
          ]
        },
        {
          "name": "Unterhaltung",
          "image": "Unterhaltung.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Unterhaltung.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Unterhaltung.Status"
            }
          ]
        },
        {
          "name": "Sicherheit",
          "image": "Sicherheit.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Sicherheit.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Sicherheit.Status"
            }
          ]
        },
        {
          "name": "Wetter",
          "image": "Wetter.webp",
          "status": [
            {
              "label": "Verbrauch",
              "value": "ioBrokerObjekte.Funktionen.Wetter.Stromverbrauch"
            },
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Funktionen.Wetter.Status"
            }
          ]
        }
      ]
    }
  ]
}

=== ldittmar81/ioBroker_dashboard/data/main/informations.json
{
  "name": "Informationen",
  "type": "informations",
  "icon": "fa-info-circle",
  "authorization": [
    "papa"
  ],
  "content": [
    {
      "category": "",
      "tiles": [
        {
          "name": "Verbrauch",
          "image": "Verbrauch.webp",
          "status": [
            {
              "label": "Stromverbrauch",
              "value": "ioBrokerObjekte.Informationen.Verbrauch.Stromverbrauch"
            },
            {
              "label": "Wasserverbrauch",
              "value": "ioBrokerObjekte.Informationen.Verbrauch.Wasserverbrauch"
            }
          ]
        },
        {
          "name": "Nicht erreichbar",
          "image": "NichtErreichbar.webp",
          "status": [
            {
              "label": "Geräte offline",
              "value": "ioBrokerObjekte.Informationen.NichtErreichbar.GeräteOffline"
            }
          ]
        },
        {
          "name": "Batterie schwach",
          "image": "BatterieSchwach.webp",
          "status": [
            {
              "label": "Anzahl",
              "value": "ioBrokerObjekte.Informationen.BatterieSchwach.AnzahlSchwach"
            }
          ]
        },
        {
          "name": "IT Infrastruktur",
          "image": "ITInfrastruktur.webp",
          "status": [
            {
              "label": "Serverstatus",
              "value": "ioBrokerObjekte.Informationen.ITInfrastruktur.Serverstatus"
            },
            {
              "label": "Netzwerk",
              "value": "ioBrokerObjekte.Informationen.ITInfrastruktur.Netzwerk"
            }
          ]
        },
        {
          "name": "Mama",
          "image": "mama.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Mama.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Mama.Anwesenheit"
            }
          ]
        },
        {
          "name": "Big Papa",
          "image": "papa.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Papa.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Papa.Anwesenheit"
            }
          ]
        },
        {
          "name": "Little Princess",
          "image": "kind1.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Kind1.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Kind1.Anwesenheit"
            }
          ]
        },
        {
          "name": "Metal Kid",
          "image": "kind2.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Kind2.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Kind2.Anwesenheit"
            }
          ]
        },
        {
          "name": "Junior Gamer",
          "image": "kind3.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Kind3.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Kind3.Anwesenheit"
            }
          ]
        },
        {
          "name": "Dog",
          "image": "hund.jpg",
          "status": [
            {
              "label": "Status",
              "value": "ioBrokerObjekte.Informationen.Dog.Status"
            },
            {
              "label": "Anwesenheit",
              "value": "ioBrokerObjekte.Informationen.Dog.Anwesenheit"
            }
          ]
        }
      ]
    }
  ]
}
